livestream:
  server:
    redis:
    nacos:
    rocketmq:
    mysql:

spring:
  application:
    name: livestream-id-generate-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 访问主库
    url: jdbc:mysql://${livestream.server.mysql}:3306/livestream_common?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123_A

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://${livestream.server.nacos}:8848?namespace=livestream-dev #&&username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: 9092