livestream:
  server:
    redis:
    nacos:
    rocketmq:
    mysql:
  rmq:
    consumer:
      nameSrv: ${livestream.server.rocketmq}:9876
      groupName: ${spring.application.name}
    producer:
      nameSrv: ${livestream.server.rocketmq}:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2


spring:
  application:
    name: livestream-user-provider
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:nacos:${livestream.server.nacos}:8848:livestream-user-shardingjdbc.yaml?namespace=livestream-dev #&&username=nacos&&password=nacos
    hikari:
      pool-name: user-pool
      minimum-idle: 100
      maximum-pool-size: 300
      idle-timeout: 60000
      connection-timeout: 4000
      max-lifetime: 60000
  data:
    redis:
      port: 6379
      host: ${livestream.server.redis}
      password: redis123
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10


dubbo:
  application:
    name: ${spring.application.name}
  registry:
    #docker启动的时候，注入host的配置
    address: nacos://${livestream.server.nacos}:8848?namespace=livestream-dev #&&username=nacos&&password=nacos
  protocol:
    name: dubbo
    port: 9090
    threadpool: fixed
    dispatcher: execution
    threads: 500
    accepts: 500
