spring:
  application:
    name: livestream-im-core-server
  cloud:
    nacos:
      discovery:
        ip: [写im-core-server的机器ip]
  data:
    redis:
      port: 6379
      host: redis-server
      password: redis123
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10
qiyu:
  im:
    tcp:
      port: 8085
    ws:
      port: 8086

  rmq:
    producer:
      nameSrv: rocketmq-server:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://nacos-server:8848?namespace=livestream-dev #&&username=nacos&&password=nacos
  protocol:
    port: 9099