livestream:
  server:
    nacos:

spring:
  application:
    name: livestream-bank-api
dubbo:
  application:
    name: livestream-bank-api
    qos-enable: false
  registry:
    address: nacos://${livestream.server.nacos}:8848?namespace=livestream-dev #&&username=nacos&&password=nacos

server:
  port: 8201
  servlet:
    context-path: /live/bank