livestream:
  server:
    redis:
    nacos:
    rocketmq:
  rmq:
    producer:
      nameSrv: ${livestream.server.rocketmq}:9876
      groupName: ${spring.application.name}
      applicationName: ${spring.application.name}
      sendMsgTimeout: 3000
      retryTimes: 2

spring:
  application:
    name: livestream-im-router-provider
  data:
    redis:
      port: 6379
      host: ${livestream.server.redis}
      password: redis123
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 10

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://${livestream.server.nacos}:8848?namespace=livestream-dev #&&username=nacos&&password=nacos
  protocol:
    port: 9098
